// Skills 数据 - 静态降级数据源
// 用于 Vercel Serverless 环境（不支持 execSync/GitHub API 调用）

const STATIC_SKILLS = [
  // Workspace Skills
  { name: 'agent-reach', desc: '全平台接入 (Twitter/Reddit/YouTube/B站等)', source: 'workspace', install: 'cp' },
  { name: 'auto-monitor', desc: '主动监控系统状态', source: 'workspace', install: 'cp' },
  { name: 'autocli', desc: '55+ 社交/内容网站 CLI', source: 'workspace', install: 'cp' },
  { name: 'clawteam', desc: '多 Agent 团队协调', source: 'workspace', install: 'cp' },
  { name: 'coding-delegate-agent', desc: '编码委托 Agent', source: 'workspace', install: 'cp' },
  { name: 'memory-curator', desc: '记忆策展人', source: 'workspace', install: 'cp' },
  { name: 'minimax-docx', desc: 'DOCX 文档创建', source: 'workspace', install: 'cp' },
  { name: 'minimax-pdf', desc: 'PDF 生成', source: 'workspace', install: 'cp' },
  { name: 'minimax-xlsx', desc: 'Excel 表格', source: 'workspace', install: 'cp' },
  { name: 'movie-subtitle-viewer', desc: '电影字幕查看', source: 'workspace', install: 'cp' },
  { name: 'openclaw-evolution', desc: '进化指南', source: 'workspace', install: 'cp' },
  { name: 'openclaw-plugin-sdk-migration', desc: '插件 SDK 迁移', source: 'workspace', install: 'cp' },
  { name: 'pptx-generator', desc: 'PPT 生成器', source: 'workspace', install: 'cp' },
  { name: 'pr-review', desc: 'PR 审查', source: 'workspace', install: 'cp' },
  { name: 'taskflow', desc: '任务流编排', source: 'workspace', install: 'cp' },
  { name: 'taskflow-inbox-triage', desc: '收件箱分类', source: 'workspace', install: 'cp' },
  { name: 'web-deploy-github', desc: 'GitHub Pages 部署', source: 'workspace', install: 'cp' },
  { name: 'x-tweet-fetcher', desc: '推文获取', source: 'workspace', install: 'cp' },
  { name: 'find-skills', desc: '技能发现', source: 'workspace', install: 'cp' },
  { name: 'dna-memory', desc: 'DNA 记忆系统', source: 'workspace', install: 'cp' },
  { name: 'holographic-memory', desc: '全息记忆', source: 'workspace', install: 'cp' },
  { name: 'lyric-sense', desc: '歌词音乐', source: 'workspace', install: 'cp' },
  { name: 'gh-issues', desc: 'GitHub Issues 管理', source: 'workspace', install: 'cp' },
  { name: 'healthcheck', desc: '安全检查', source: 'workspace', install: 'cp' },
  { name: 'self-health-monitor', desc: '健康监控', source: 'workspace', install: 'cp' },
  { name: 'self-improving', desc: '自我改进', source: 'workspace', install: 'cp' },
  { name: 'summarize', desc: '文本摘要', source: 'workspace', install: 'cp' },
  { name: 'planning-with-files', desc: '文件规划', source: 'workspace', install: 'cp' },
  { name: 'openclaw-pr-maintainer', desc: 'PR 维护', source: 'workspace', install: 'cp' },
  { name: 'obsidian', desc: 'Obsidian 笔记', source: 'workspace', install: 'cp' },
  { name: 'github', desc: 'GitHub CLI', source: 'workspace', install: 'cp' },
  { name: 'scrapling-official', desc: '智能爬虫', source: 'workspace', install: 'cp' },
  { name: 'openclaw-auto-updater', desc: '自动更新', source: 'workspace', install: 'cp' },
  { name: 'myclaw-backup', desc: 'MyClaw 备份', source: 'workspace', install: 'cp' },
  { name: 'clawhub', desc: 'ClawHub CLI', source: 'workspace', install: 'cp' },
  { name: 'create-agent-skills', desc: '创建 Agent Skills', source: 'workspace', install: 'cp' },
  { name: 'openclaw-tavily-search', desc: 'Tavily 搜索', source: 'workspace', install: 'cp' },
  { name: 'clawpi-redpacket-monitor', desc: '红包监控', source: 'workspace', install: 'cp' },
  { name: 'gateway-watchdog-xiaoxi', desc: '网关看门狗', source: 'workspace', install: 'cp' },
  { name: 'cognitive-memory', desc: '认知记忆系统', source: 'workspace', install: 'cp' },
  { name: 'coding-agent', desc: '编码 Agent', source: 'workspace', install: 'cp' },
  { name: 'self-improving-agent', desc: '自我进化 Agent', source: 'workspace', install: 'cp' },
  { name: 'self-reflection', desc: '自我反思', source: 'workspace', install: 'cp' },
  { name: 'avatar-helper', desc: '头像助手', source: 'workspace', install: 'cp' },

  // OpenClaw 内置 Skills
  { name: 'weather', desc: '天气查询', source: 'openclaw', install: 'cp' },
  { name: 'blucli', desc: 'BluOS 播放器控制', source: 'openclaw', install: 'cp' },
  { name: 'eightctl', desc: 'Eight Sleep 智能床垫', source: 'openclaw', install: 'cp' },
  { name: 'mcporter', desc: 'MCP 工具集', source: 'openclaw', install: 'cp' },
  { name: 'newsnow', desc: '聚合新闻源', source: 'openclaw', install: 'cp' },
  { name: 'tmux', desc: 'tmux 会话控制', source: 'openclaw', install: 'cp' },
  { name: 'tavily', desc: 'AI 搜索', source: 'openclaw', install: 'cp' },
  { name: 'multi-search-engine', desc: '多搜索引擎', source: 'openclaw', install: 'cp' },
  { name: 'fluxa-agent-wallet', desc: 'FluxA 钱包', source: 'openclaw', install: 'cp' },
  { name: 'stealth-browser', desc: '反检测浏览器', source: 'openclaw', install: 'cp' },
  { name: 'video-frames', desc: '视频帧提取', source: 'openclaw', install: 'cp' },
  { name: 'skill-creator', desc: '技能创建', source: 'openclaw', install: 'cp' },
  { name: 'session-logs', desc: '会话日志', source: 'openclaw', install: 'cp' },
  { name: 'node-connect', desc: '节点连接', source: 'openclaw', install: 'cp' },

  // ClawHub/Repo 常用 Skills
  { name: 'bird', desc: 'Twitter 发推', source: 'clawhub', install: 'clawdhub' },
  { name: 'powerpoint-pptx', desc: 'PPT 生成', source: 'clawhub', install: 'clawdhub' },
  { name: 'chrome-cdp', desc: 'Chrome CDP 控制', source: 'clawhub', install: 'clawdhub' },
  { name: 'clawbot-market', desc: 'ClawBot 市场', source: 'clawhub', install: 'clawdhub' },
  { name: 'companion-lobster', desc: '陪伴型小龙虾', source: 'clawhub', install: 'clawdhub' },
  { name: 'cross-bot-communication', desc: '跨 Bot 通信', source: 'clawhub', install: 'clawdhub' },
  { name: 'elite-longterm-memory', desc: '精英长期记忆', source: 'clawhub', install: 'clawdhub' },
  { name: 'lobster-cultivation', desc: '小龙虾养殖', source: 'clawhub', install: 'clawdhub' },
  { name: 'memu', desc: '内存工具', source: 'clawhub', install: 'clawdhub' },
  { name: 'pinchtab-helper', desc: '浏览器自动化', source: 'clawhub', install: 'clawdhub' },
  { name: 'proactive-solvr', desc: '主动解决者', source: 'clawhub', install: 'clawdhub' },
  { name: 'self-driven', desc: '自驱动', source: 'clawhub', install: 'clawdhub' },
  { name: 'superpowers', desc: '超能力', source: 'clawhub', install: 'clawdhub' },
  { name: 'pentest-learning-skill', desc: '渗透学习', source: 'clawhub', install: 'clawdhub' },
  { name: 'fabric', desc: 'Fabric 工具', source: 'clawhub', install: 'clawdhub' },
  { name: 'files', desc: '文件管理', source: 'clawhub', install: 'clawdhub' },
  { name: 'gogcli', desc: 'Google 服务 CLI', source: 'clawhub', install: 'clawdhub' },
  { name: 'epro-memory', desc: 'EPRO 记忆', source: 'clawhub', install: 'clawdhub' },
  { name: 'hermes-agent', desc: 'Hermes Agent', source: 'clawhub', install: 'clawdhub' },
  { name: 'openclaw-qa', desc: '问答系统', source: 'clawhub', install: 'clawdhub' },
];

export default STATIC_SKILLS;
